### PR TITLE
NodeCLI and Validator CLI

### PR DESCRIPTION
**Pull request by ebruengwall-ant**

### CODE REVIEW

**Review by badrogger — CHANGES_REQUESTED** [review]
For version develop.20 we also need DOCKER_USERNAME and DOCKER_PASSWORD parameters

**Review by cstrangedk — DISMISSED** [review]

**Review by christineRPM — DISMISSED** [review]
approved

**Review by badrogger — DISMISSED** [review]
Lgtm

**Review by christineRPM — DISMISSED** [review]
approved

**Review by christineRPM — DISMISSED** [review]
approved

**Review by payvint — DISMISSED** [review]
Nice update!

**Review by badrogger — APPROVED** [review]
Good!

**Review by payvint — APPROVED** [review]
Nice!

**Pull request merged**
