### PR TITLE
Feat/update docs

### PR DESCRIPTION
**Pull request by gannakulikova**

### CODE REVIEW

**Review by dphoursa — DISMISSED** [review]

**Review by christineRPM — DISMISSED** [review]
approved

**Comment by ebruengwall-ant** [comment]
Had to rebase commits because of not signed commits

**Review by christineRPM — APPROVED** [review]
approved

**Review by ebruengwall-ant — APPROVED** [review]
Merged the updates with a signed commit into the dev branch and Checked the stage environment. All looks good after the deployment

**Review by dphoursa — APPROVED** [review]

**Pull request merged**
